#!/bin/bash
##[ Ficha ]##################################################
#
# Nome: Emmi-procurar
# Escrito por: Slackjeff <lrcjefferson@gmail.com>
# Criado em: 10/03/2017
# Ultima atualização: N/A
#
##[ Descrição ]##############################################
#
# Script para procurar pacotes
#
##[ Inicio do Script ]#######################################

# Não é root, logar como root
if [ "$(id -u)" != "0" ]
then
        echo "$(tput setaf 2)Você precisa de poderes de super vaca, para rodar este programa."
	echo "Deseja logar como root? [S/n]"
	read resposta
	test "$resposta" = "n" && exit
	su -c "emmi-procurar $1"

else

        echo "Super vaca ativada, $(tput setaf 3)vamos procurar o pacote" ;sleep 1
	echo "Iniciando a procura..." ;sleep 1
	apt search $1
fi
