#!/bin/bash
#Emmi Inteligente versão 1.0
#Emmi Linux

# Não é root, logar como root
if [ "$(id -u)" != "0" ]
then
        echo "$(tput setaf 2)Você precisa de poderes de super vaca, para rodar este programa."
        su -l
else
        echo "Super vaca ativada, $(tput setaf 3)vamos verificar a integridade do pacote" ;sleep 1
fi
#fim

echo "$(tput setaf 1)Verificando integridade dos pacotes " ;sleep 1
apt check
echo "$(tput setaf 2)Concluído..." ;sleep 1
