#!/bin/bash
#Emmi Inteligente versão 1.0
#Emmi Linux

# if not root, run as root
if (( $EUID != 0 )); then
    echo "Favor entrar como root"
    exit
fi

echo "$(tput setaf 1)Verificando integridade dos pacotes " ;sleep 1
apt check
echo "$(tput setaf 2)Concluído..." ;sleep 1