#!/bin/bash
##[ Ficha ]##################################################
#
# Nome: Emmi-manual
# Escrito por: Slackjeff <lrcjefferson@gmail.com>
# Criado em: 10/03/2017
# Ultima atualização: N/A
#
##[ Descrição ]##############################################
#
# Script que dá o manual para o usuário
#
##[ Inicio do Script ]#######################################

man $1 | less
