#!/bin/bash
#Emmi Inteligente versão 1.0
#Emmi Linux

# Não é root, logar como root
if (( $EUID != 0 )); then
    echo "$(tput setaf 1)Favor entrar como root, use o comando $(tput setaf 2)su"
    exit
fi

echo "$(tput setaf 1)Iniciando limpeza" ;sleep 1
apt clean
echo "$(tput setaf 2)..." ;sleep 1
apt autoclean
echo "$(tput setaf 2)Concluímos a limpeza, tenha um ótimo dia!"