#!/bin/bash
#Emmi Inteligente versão 1.0
#Emmi Linux

# Não é root, logar como root
if (( $EUID != 0 ))
then
        echo "Você não está logado" ;sleep 1
        su -l
else
        echo "Com grandes poderes vem grandes responsabilidades #root"
fi
#fim

echo "$(tput setaf 1)Iniciando limpeza" ;sleep 1
apt clean
echo "$(tput setaf 2)..." ;sleep 1
apt autoclean
echo "$(tput setaf 2)Concluímos a limpeza, tenha um ótimo dia!"
