#!/bin/bash

#Emmi Inteligente versão 1.0
#Emmi Linux

# Não é root, logar como root
if (( $EUID != 0 ))
then
        echo "Você não está logado" ;sleep 1
        su -l
else
        echo "Com grandes poderes vem grandes responsabilidades #root"
fi
#fim

echo "Iniciando a procura" ;sleep 1
apt search $1
