#!/bin/bash

#Emmi Inteligente versão 1.0
#Emmi Linux


# Não é root, logar como root
if (( $EUID != 0 ))
then
        echo "Você não está logado" ;sleep 1
        su -l
else
        echo "Com grandes poderes vem grandes responsabilidades #root"
fi
#fim

echo "$(tput setaf 2)Nunca se esqueça de atualizar o repositório, $(tput setaf 5)utilize emmi-atualizar." ;sleep 1
echo
apt install $1
echo "$(tput setaf 3)Concluímos...Tenha um bom dia!"
