#!/bin/bash
##[ Ficha ]##################################################
#
# Nome: Emmi-atualizar-versao
# Escrito por: Slackjeff <lrcjefferson@gmail.com>
# Criado em: 10/03/2017
# Ultima atualização: N/A
#
##[ Descrição ]##############################################
#
# Script que tem como objetivo de facilitar
# Trazendo 6 ferramentas uteis no dia-dia.
#
##[ Inicio do Script ]#######################################

# Não é root, logar como root
if [ "$(id -u)" != "0" ]
then
        echo "$(tput setaf 2)Você precisa de poderes de super vaca, para rodar este programa."
	echo "Você deseja logar como root? [S/n]"
	read resposta
	test "$resposta" = "n" && exit
	su -c "emmi-atualizar-versao"

else
        echo "Super vaca ativada, vamos atualizar o a versão" ;sleep 1
	apt-get moo ;sleep 1
	apt-get update
	echo "Update Concluído..." ;sleep 2
	apt dist-upgrade
	echo "Concluído...Tenha um bom dia!"
fi



